import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Main {

    // Instantiate the Scanner as a static variable
    private static final Scanner scanner = new Scanner(System.in);

    // Starts the game calling the guessGame method and closes the scanner at the end.
    public static void main(String[] args) {
        guessGame();
        scanner.close();
    }

    /* Main logic for the Guess Game.
     * Handles user input, game flow, and scoring.
     */
    private static void guessGame() {

        int choice = 0;
        int accumulatedScore = 0;
        List<Integer> correctNumbers = new ArrayList<>();
        List<Integer> wrongNumbers = new ArrayList<>();

        System.out.println("\n* * * * * J O G O   D O   A D I V I N H A * * * * *\n");
        System.out.println("""
                Bem vindo ao Jogo!
                
                A qualquer momento que deseje encerrar o jogo e sair digite '0' (zero)
                """);
        showDifficultyMenu();
        do {
            choice = readInteger();
            if (choice == 0) {
                exitMessage();
                return;
            }
            if (choice < 1 || choice > 3)
                showInvalidNumberMessage();
        } while (choice < 0 || choice > 3);

        int max = maxNumber(choice);

        while (true) {

            int userNumber = readUserNumber(max);
            if (userNumber == 0) {
                showResult(accumulatedScore, correctNumbers, wrongNumbers);
                exitMessage();
                return;
            }
            int systemNumber = drawnNumber(max);
            int scored = compareNumbers(systemNumber, userNumber);
            accumulatedScore += scored;

            if (scored == 10)
                correctNumbers.add(userNumber);
            else
                wrongNumbers.add(userNumber);

            showScore(scored, systemNumber, accumulatedScore);
        }
    }

    //Displays the difficulty menu with options for the user to choose.
    private static void showDifficultyMenu() {
        System.out.println("Escolha o nível de dificuldade desejado: ");
        System.out.println("""
                1 - Fácil
                2 - Médio
                3 - Difícil""");
        System.out.print("Opção: ");
    }

    /* Reads an integer from the user input.
     * Handles invalid input by prompting the user to enter a valid number.
     */
    private static int readInteger() {
        try {
            return scanner.nextInt();
        } catch (Exception e) {
            showInvalidNumberMessage();
            scanner.nextLine();
            return readInteger();
        }
    }

    // Draws a random number between 1 and the specified maximum value.
    private static int drawnNumber(int max) {
        return (int) (Math.random() * max) + 1;
    }

    //Returns the maximum number based on the chosen difficulty level.
    private static int maxNumber(int choice) {
        return switch (choice) {
            case 1 -> 10;
            case 2 -> 50;
            case 3 -> 100;
            default -> 0;
        };
    }

    /* Reads a number from the user within the specified range between 0 and 'max'.
     *  Prompts the user until a valid number is entered.
     */
    private static int readUserNumber(int max) {
        int number = 0;
        do {
            System.out.print("Digite um número inteiro entre 1 e " + max + " ou '0' para sair: ");
            number = readInteger();
        } while (number < 0 || number > max);

        return number;
    }

    /**
     * Compares the system-generated number with the user's guess.
     * Awards points based on the accuracy of the guess.
     *
     * @param systemNumber The number generated by the system.
     * @param userNumber   The number guessed by the user.
     * @return The points scored by the user.
     */
    private static int compareNumbers(int systemNumber, int userNumber) {
        return (userNumber == systemNumber) ? 10 : (Math.abs(systemNumber - userNumber) == 1) ? 5 : 0;
    }

    //Displays a farewell message when the user exits the game.
    private static void exitMessage() {
        System.out.println("\nObrigado por jogar! Até a próxima!");
    }

    // Displays the score for the current round and the total accumulated score.
    private static void showScore(int scored, int systemNumber, int accumulatedScore) {
        switch (scored) {
            case 10 -> System.out.println("Parabéns! Você acertou o número e ganhou 10 pontos!");
            case 5 -> System.out.println("Quase lá! Você estava a 1 de distância do número sorteado. Fez 5 pontos.");
            case 0 -> System.out.println("Que pena! O número sorteado era " + systemNumber + ".");
            default -> System.out.println("*** Não identificamos sua pontuação! ***");
        }
        System.out.println("Pontuação total: " + accumulatedScore);
    }

    //Displays the final results of the game, including the total score, correct numbers, and wrong numbers.
    private static void showResult(int accumulatedScore, List<Integer> correctNumbers, List<Integer> wrongNumbers) {
        System.out.println("\nVocê alcançou " + accumulatedScore + " pontos!\nNúmeros acertados: "
                + correctNumbers.toString() + "\nNúmeros errados: " + wrongNumbers.toString());
    }

    //Displays a message when the user enters an invalid number.
    private static void showInvalidNumberMessage() {
        System.out.print("Entrada inválida. Digite novamente: ");
    }
}
